// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 02 Dec 2015 07:09:32 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.19102.0")]
[assembly: AssemblyFileVersion("1.0.19102.709")]
