// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 18 Nov 2015 08:21:00 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.19018.0")]
[assembly: AssemblyFileVersion("1.0.19018.821")]
