// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 27 Nov 2015 10:08:55 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.19027.0")]
[assembly: AssemblyFileVersion("1.0.19027.1008")]
